import React from 'react'
import Head from 'next/head'

function PageLayOut({children,title}) {


  return (

    <div>
        <Head>
            
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/apertura.svg"/>
            <link href="https://fonts.googleapis.com/css2?family=Mukta+Mahee:wght@300&display=swap" rel="stylesheet"></link>
        </Head>
        <main>
            {children}
        </main>

    </div>
  )
}

export default PageLayOut;